### ISSUE TITLE
キャラクター選択画面とシステムの実装

### ISSUE THREAD

**Issue by KAITO-I** [KAITO-I/BattleBeat#15]
## 概要
キャラクターのアイコンが4つ配置され、選択及び決定の
操作が行える状態。この時点で2P対応が望ましい。

## 実装内容
- [ ] 同時操作
- [ ] 選択したキャラクターがわかるように

**Comment by SA371516** [comment]
選択システム実装完了
あとは、選択されたデータをどのように送るのか、どこに送るのかが知りたいです
