### ISSUE TITLE
リザルトの作成

### ISSUE THREAD

**Issue by SA371516** [KAITO-I/BattleBeat#20]

**Comment by SA371516** [comment]
位置を指定されたように直しました
あと、どのボタンを押したらどこに飛ぶのかが知りたいです

**Comment by Hkazumasa** [comment]
仕様書にある通り二通りありまして、
モード選択画面に戻るのと、キャラ選択に戻るのとで２種類あります。
ただちょっと思ったのがこれをボタンで指定するんじゃなくて
なにかＵＩを配置して選ばせるという方法のほうがプレイヤーは見やすい気がするので
ＵＩでやってみてもいいかディレクターと相談します。
ただ今やることとすれば
モード選択画面に戻るのとキャラ選択画面に戻る二通りがあるということです。
この連結を今は行っておいてください。

**Comment by SA371516** [comment]
了解でっす
とりあえず遷移はできているので、スクリプトにコメントで書けたらなと思っていたので大丈夫です
決まり次第また連絡ください
