### ISSUE TITLE
プロジェクトが送信できない

### ISSUE THREAD

**Issue by SA371516** [KAITO-I/BattleBeat#5]
移動と移動制御は終わったんだが、URLがNot foundでプロジェクトが送れないのだが、どのURLを使えばええのん？

**Comment by KAITO-I** [comment]
コミットできないってこと？

**Comment by KAITO-I** [comment]
https://github.com/KAITO-I/BattleBeat.git
このURL使えば正常にコミットできると思う

**Comment by SA371516** [comment]
学校の別のパソコンを使用してみたら無事Githubできました
ご迷惑をおかけしました

**Comment by KAITO-I** [comment]
解決できたようで何よりです…！
